# Generated by Django 5.2.8 on 2025-12-25 21:16

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='achievement',
            unique_together={('user', 'achievement_type', 'title')},
        ),
    ]
