# Generated by Django 5.2.8 on 2025-12-25 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0002_alter_answeroption_options_alter_quiz_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructorprofile',
            name='certifications',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='instructorprofile',
            name='linkedin_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='instructorprofile',
            name='portfolio_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='instructorprofile',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to='instructor_resumes/'),
        ),
        migrations.AddField(
            model_name='instructorprofile',
            name='sample_course_topic',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='instructorprofile',
            name='teaching_experience',
            field=models.TextField(blank=True, help_text='Previous teaching experience'),
        ),
        migrations.AddField(
            model_name='instructorprofile',
            name='why_teach',
            field=models.TextField(blank=True, help_text='Why do you want to teach?'),
        ),
        migrations.AddField(
            model_name='instructorprofile',
            name='years_of_experience',
            field=models.IntegerField(default=0, help_text='Years of professional experience'),
        ),
    ]
