# Generated by Django 5.2.8 on 2026-01-15 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0003_instructorprofile_certifications_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='video_file',
            field=models.FileField(blank=True, help_text='Uploaded video file (alternative to video_url)', null=True, upload_to='course_videos/'),
        ),
    ]
