# Generated by Django 5.2.8 on 2026-01-15 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0004_lesson_video_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='quiz_auto_generated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lesson',
            name='quiz_generation_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('disabled', 'Disabled')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='lesson',
            name='quiz_required',
            field=models.BooleanField(default=True, help_text='Students must pass quiz to complete this lesson'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='requires_previous_completion',
            field=models.BooleanField(default=True, help_text='Student must complete previous lesson first'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='video_transcript',
            field=models.TextField(blank=True, help_text='Extracted transcript for quiz generation'),
        ),
        migrations.AddField(
            model_name='lessonprogress',
            name='best_quiz_score',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Best score achieved on quiz (percentage)', max_digits=5),
        ),
        migrations.AddField(
            model_name='lessonprogress',
            name='quiz_attempts',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='lessonprogress',
            name='quiz_passed',
            field=models.BooleanField(default=False),
        ),
    ]
